apiVersion: apps/v1
kind: Deployment
metadata:
  name: phx-chat
  labels:
    app: phx-chat
spec:
  selector:
    matchLabels:
      app:  phx-chat

  # sometimes using one or three replica to troubleshoot redis
  replicas: 3
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: phx-chat
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        # this one a random number... but is it called / pulled at runtime or at compile time? WE'LL FIND OUT!
        - image: eqmvii/pivate_phx_chat:2
          imagePullPolicy: Always
          name: phx-chat
          ports:
            - containerPort: 4000

# TODO ERIC: Consider exploring environment variable introspectoin:
# env:
#   - name: MY_POD_NAME
#     valueFrom:
#       fieldRef:
#         fieldPath: metadata.name



